__d(
  'CometTextWithEntitiesRelay_textWithEntities$normalization.graphql',
  [],
  function (a, b, c, d, e, f) {
    'use strict';
    a = (function () {
      var a = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'length',
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'offset',
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'id',
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: '__typename',
          storageKey: null,
        },
        e = [{ kind: 'Literal', name: 'delight_surface', value: 'COMMENT' }],
        f = [c],
        g = { kind: 'Variable', name: 'scale', variableName: 'scale' },
        h = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'height',
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'uri',
          storageKey: null,
        },
        j = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'width',
          storageKey: null,
        },
        k = {
          kind: 'InlineFragment',
          selections: f,
          type: 'Node',
          abstractKey: '__isNode',
        },
        l = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'name',
          storageKey: null,
        },
        m = [c, l],
        n = {
          alias: null,
          args: null,
          concreteType: 'WorkForeignEntityInfo',
          kind: 'LinkedField',
          name: 'work_foreign_entity_info',
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: 'ScalarField',
              name: 'type',
              storageKey: null,
            },
          ],
          storageKey: null,
        };
      return {
        kind: 'SplitOperation',
        metadata: {},
        name: 'CometTextWithEntitiesRelay_textWithEntities$normalization',
        selections: [
          {
            alias: null,
            args: null,
            concreteType: 'DelightAtRange',
            kind: 'LinkedField',
            name: 'delight_ranges',
            plural: !0,
            selections: [
              a,
              b,
              {
                alias: null,
                args: null,
                concreteType: 'TextDelightCampaign',
                kind: 'LinkedField',
                name: 'campaign',
                plural: !1,
                selections: [
                  c,
                  d,
                  {
                    alias: null,
                    args: e,
                    concreteType: 'TextDelightStylePair',
                    kind: 'LinkedField',
                    name: 'delight_styles',
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'style',
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'value',
                        storageKey: null,
                      },
                    ],
                    storageKey: 'delight_styles(delight_surface:"COMMENT")',
                  },
                  {
                    alias: null,
                    args: e,
                    concreteType: 'DelightsAnimation',
                    kind: 'LinkedField',
                    name: 'delight_asset',
                    plural: !1,
                    selections: f,
                    storageKey: 'delight_asset(delight_surface:"COMMENT")',
                  },
                  {
                    alias: null,
                    args: null,
                    kind: 'ScalarField',
                    name: 'text_enrichment_url',
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: 'ImageAtRange',
            kind: 'LinkedField',
            name: 'image_ranges',
            plural: !0,
            selections: [
              a,
              b,
              {
                alias: null,
                args: null,
                concreteType: null,
                kind: 'LinkedField',
                name: 'entity_with_image',
                plural: !1,
                selections: [
                  d,
                  {
                    alias: null,
                    args: [g],
                    concreteType: 'Image',
                    kind: 'LinkedField',
                    name: 'image',
                    plural: !1,
                    selections: [
                      h,
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'scale',
                        storageKey: null,
                      },
                      i,
                      j,
                    ],
                    storageKey: null,
                  },
                  k,
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: 'InlineStyleAtRange',
            kind: 'LinkedField',
            name: 'inline_style_ranges',
            plural: !0,
            selections: [
              a,
              b,
              {
                alias: null,
                args: null,
                kind: 'ScalarField',
                name: 'inline_style',
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: 'AggregatedEntitiesAtRange',
            kind: 'LinkedField',
            name: 'aggregated_ranges',
            plural: !0,
            selections: [
              a,
              b,
              {
                alias: null,
                args: null,
                kind: 'ScalarField',
                name: 'count',
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: null,
                kind: 'LinkedField',
                name: 'sample_entities',
                plural: !0,
                selections: [
                  d,
                  {
                    kind: 'InlineFragment',
                    selections: m,
                    type: 'User',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: m,
                    type: 'Page',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      c,
                      {
                        alias: 'name',
                        args: null,
                        kind: 'ScalarField',
                        name: 'username',
                        storageKey: null,
                      },
                    ],
                    type: 'InstagramUserV2',
                    abstractKey: null,
                  },
                  k,
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: 'EntityAtRange',
            kind: 'LinkedField',
            name: 'ranges',
            plural: !0,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: null,
                kind: 'LinkedField',
                name: 'entity',
                plural: !1,
                selections: [
                  d,
                  { kind: 'TypeDiscriminator', abstractKey: '__isEntity' },
                  {
                    alias: null,
                    args: [{ kind: 'Literal', name: 'site', value: 'comet' }],
                    kind: 'ScalarField',
                    name: 'url',
                    storageKey: 'url(site:"comet")',
                  },
                  {
                    alias: 'mobileUrl',
                    args: [{ kind: 'Literal', name: 'site', value: 'mobile' }],
                    kind: 'ScalarField',
                    name: 'url',
                    storageKey: 'url(site:"mobile")',
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      c,
                      {
                        kind: 'InlineFragment',
                        selections: [
                          {
                            alias: 'profile_url',
                            args: null,
                            kind: 'ScalarField',
                            name: 'url',
                            storageKey: null,
                          },
                        ],
                        type: 'Entity',
                        abstractKey: '__isEntity',
                      },
                    ],
                    type: 'Actor',
                    abstractKey: '__isActor',
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        args: null,
                        documentName:
                          'CometTextWithEntitiesRelay_textWithEntities',
                        fragmentName:
                          'GroupsCometHashtagsStoryMessageHashtagLink_hashtag',
                        fragmentPropName: 'hashtag',
                        kind: 'ModuleImport',
                      },
                    ],
                    type: 'GroupHashtag',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        args: null,
                        documentName:
                          'CometTextWithEntitiesRelay_textWithEntities',
                        fragmentName: 'PagesCometPageLink_page',
                        fragmentPropName: 'page',
                        kind: 'ModuleImport',
                      },
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'category_type',
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'verification_status',
                        storageKey: null,
                      },
                      c,
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'is_verified',
                        storageKey: null,
                      },
                    ],
                    type: 'Page',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        args: null,
                        documentName:
                          'CometTextWithEntitiesRelay_textWithEntities',
                        fragmentName: 'ProfileGeminiWeakReferenceLink_user',
                        fragmentPropName: 'user',
                        kind: 'ModuleImport',
                      },
                      n,
                      {
                        alias: null,
                        args: null,
                        concreteType: 'WorkUserInfo',
                        kind: 'LinkedField',
                        name: 'work_info',
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: 'ScalarField',
                            name: 'is_active_account',
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                    ],
                    type: 'User',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        args: null,
                        documentName:
                          'CometTextWithEntitiesRelay_textWithEntities',
                        fragmentName:
                          'GroupsCometCustomCommandsLink_groupSlashCommand',
                        fragmentPropName: 'groupSlashCommand',
                        kind: 'ModuleImport',
                      },
                    ],
                    type: 'GroupCustomSlashCommand',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'external_url',
                        storageKey: null,
                      },
                    ],
                    type: 'ExternalUrl',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'time_index',
                        storageKey: null,
                      },
                    ],
                    type: 'VideoTimeIndex',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: null,
                        kind: 'LinkedField',
                        name: 'web_link',
                        plural: !1,
                        selections: [
                          d,
                          {
                            alias: null,
                            args: null,
                            kind: 'ScalarField',
                            name: 'url',
                            storageKey: null,
                          },
                          {
                            kind: 'InlineFragment',
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: 'ScalarField',
                                name: 'fbclid',
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: 'ScalarField',
                                name: 'lynx_mode',
                                storageKey: null,
                              },
                            ],
                            type: 'ExternalWebLink',
                            abstractKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                    ],
                    type: 'WebLinkable',
                    abstractKey: '__isWebLinkable',
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      n,
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'is_multi_company_group',
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'work_official_status',
                        storageKey: null,
                      },
                    ],
                    type: 'Group',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        alias: 'imageScaledForFeed',
                        args: [
                          g,
                          { kind: 'Literal', name: 'width', value: 680 },
                        ],
                        concreteType: 'Image',
                        kind: 'LinkedField',
                        name: 'image',
                        plural: !1,
                        selections: [h, i, j],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'accessibility_caption',
                        storageKey: null,
                      },
                    ],
                    type: 'Photo',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: 'Group',
                        kind: 'LinkedField',
                        name: 'target_group',
                        plural: !1,
                        selections: [
                          {
                            args: null,
                            documentName:
                              'CometTitleSentenceGroupJoinButtonRenderer_entity',
                            fragmentName:
                              'CometFeedStoryCommunityAttributionTitleJoinButton_group',
                            fragmentPropName: 'group',
                            kind: 'ModuleImport',
                          },
                          c,
                        ],
                        storageKey: null,
                      },
                    ],
                    type: 'TitleSentenceGroupJoinButton',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'deep_link_number',
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: 'Page',
                        kind: 'LinkedField',
                        name: 'page',
                        plural: !1,
                        selections: [
                          {
                            alias: 'use_whatsapp_deeplinks_plugin',
                            args: [
                              {
                                kind: 'Literal',
                                name: 'gk_name',
                                value: 'bmxm_ctwa_perf_page_launch_h22022',
                              },
                            ],
                            concreteType: 'EntGKCheck',
                            kind: 'LinkedField',
                            name: 'gk_check',
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: 'ScalarField',
                                name: 'passes_gk',
                                storageKey: null,
                              },
                            ],
                            storageKey:
                              'gk_check(gk_name:"bmxm_ctwa_perf_page_launch_h22022")',
                          },
                          c,
                        ],
                        storageKey: null,
                      },
                    ],
                    type: 'PageWhatsAppNumber',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      l,
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'ticker_symbol',
                        storageKey: null,
                      },
                    ],
                    type: 'KGTickerNode',
                    abstractKey: null,
                  },
                  {
                    kind: 'InlineFragment',
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: 'ScalarField',
                        name: 'snapshot_url',
                        storageKey: null,
                      },
                      {
                        kind: 'InlineFragment',
                        selections: [
                          {
                            kind: 'InlineFragment',
                            selections: [
                              {
                                alias: null,
                                args: null,
                                concreteType: 'DataSnapshotMetadata',
                                kind: 'LinkedField',
                                name: 'metadata',
                                plural: !1,
                                selections: [
                                  {
                                    alias: null,
                                    args: null,
                                    kind: 'ScalarField',
                                    name: 'ratio',
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            type: 'XFBProdQuartzVizirSnapshot',
                            abstractKey: null,
                          },
                        ],
                        type: 'Entity',
                        abstractKey: '__isEntity',
                      },
                    ],
                    type: 'XFBProdQuartzVizirSnapshot',
                    abstractKey: null,
                  },
                  k,
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: 'ScalarField',
                name: 'entity_is_weak_reference',
                storageKey: null,
              },
              a,
              b,
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: 'ColorAtRange',
            kind: 'LinkedField',
            name: 'color_ranges',
            plural: !0,
            selections: [
              a,
              b,
              {
                alias: null,
                args: null,
                kind: 'ScalarField',
                name: 'hex_rgb_color_with_pound_key',
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: 'ScalarField',
            name: 'text',
            storageKey: null,
          },
        ],
      };
    })();
    e.exports = a;
  },
  null,
);
