__d(
  'StoriesCreateSATPPreviewQuery.graphql',
  [
    'CometTextWithEntitiesRelay_textWithEntities$normalization.graphql',
    'StoriesCreateSATPPreviewQuery_facebookRelayOperation',
  ],
  function (a, b, c, d, e, f) {
    'use strict';
    a = (function () {
      var a = [
          { defaultValue: null, kind: 'LocalArgument', name: 'cardID' },
          { defaultValue: null, kind: 'LocalArgument', name: 'scale' },
        ],
        c = [{ kind: 'Variable', name: 'id', variableName: 'cardID' }],
        d = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: '__typename',
          storageKey: null,
        },
        e = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'color',
          storageKey: null,
        },
        f = [
          {
            alias: null,
            args: null,
            kind: 'ScalarField',
            name: 'uri',
            storageKey: null,
          },
        ],
        g = {
          args: null,
          fragment: b(
            'CometTextWithEntitiesRelay_textWithEntities$normalization.graphql',
          ),
          kind: 'FragmentSpread',
        },
        h = {
          alias: null,
          args: null,
          kind: 'ScalarField',
          name: 'id',
          storageKey: null,
        },
        i = { kind: 'Variable', name: 'scale', variableName: 'scale' };
      return {
        fragment: {
          argumentDefinitions: a,
          kind: 'Fragment',
          metadata: null,
          name: 'StoriesCreateSATPPreviewQuery',
          selections: [
            {
              alias: 'card',
              args: c,
              concreteType: null,
              kind: 'LinkedField',
              name: 'node',
              plural: !1,
              selections: [
                {
                  kind: 'InlineFragment',
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: 'StoryBackgroundInfo',
                      kind: 'LinkedField',
                      name: 'story_default_background',
                      plural: !1,
                      selections: [
                        {
                          args: null,
                          kind: 'FragmentSpread',
                          name: 'StoriesCardComposerFormat_defaultBackground',
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: 'TextWithEntities',
                      kind: 'LinkedField',
                      name: 'message',
                      plural: !1,
                      selections: [
                        {
                          args: null,
                          kind: 'FragmentSpread',
                          name: 'StoriesCardComposerFormat_message',
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: 'TextFormatMetadata',
                      kind: 'LinkedField',
                      name: 'text_format_metadata',
                      plural: !1,
                      selections: [
                        {
                          args: null,
                          kind: 'FragmentSpread',
                          name: 'StoriesCardComposerFormat_textFormatMetaData',
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      args: null,
                      kind: 'FragmentSpread',
                      name: 'StoriesCardComposerFormat_story',
                    },
                  ],
                  type: 'Story',
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: 'Query',
          abstractKey: null,
        },
        kind: 'Request',
        operation: {
          argumentDefinitions: a,
          kind: 'Operation',
          name: 'StoriesCreateSATPPreviewQuery',
          selections: [
            {
              alias: 'card',
              args: c,
              concreteType: null,
              kind: 'LinkedField',
              name: 'node',
              plural: !1,
              selections: [
                d,
                {
                  kind: 'InlineFragment',
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: 'StoryBackgroundInfo',
                      kind: 'LinkedField',
                      name: 'story_default_background',
                      plural: !1,
                      selections: [
                        e,
                        {
                          alias: null,
                          args: null,
                          concreteType: 'GradientData',
                          kind: 'LinkedField',
                          name: 'gradient',
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: 'ScalarField',
                              name: 'css',
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: 'Image',
                          kind: 'LinkedField',
                          name: 'portrait_image',
                          plural: !1,
                          selections: f,
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: 'TextWithEntities',
                      kind: 'LinkedField',
                      name: 'message',
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'text',
                          storageKey: null,
                        },
                        g,
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: 'TextFormatMetadata',
                      kind: 'LinkedField',
                      name: 'text_format_metadata',
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'text_align',
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'font_style',
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'font_weight',
                          storageKey: null,
                        },
                        e,
                        {
                          alias: null,
                          args: null,
                          concreteType: 'InspirationsCustomFont',
                          kind: 'LinkedField',
                          name: 'inspirations_custom_font_object',
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: 'ScalarField',
                              name: 'font_postscript_name',
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: 'ScalarField',
                              name: 'font_url',
                              storageKey: null,
                            },
                            h,
                          ],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: [i],
                          concreteType: 'Image',
                          kind: 'LinkedField',
                          name: 'portrait_background_image',
                          plural: !1,
                          selections: f,
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'background_color',
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'background_gradient_color',
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'background_gradient_direction',
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: 'TextWithEntities',
                      kind: 'LinkedField',
                      name: 'activity_description',
                      plural: !1,
                      selections: [g],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: [{ kind: 'Literal', name: 'first', value: 1 }],
                      concreteType: 'InlineActivitiesConnection',
                      kind: 'LinkedField',
                      name: 'inline_activities',
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: 'InlineActivity',
                          kind: 'LinkedField',
                          name: 'nodes',
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: 'TaggableActivityIcon',
                              kind: 'LinkedField',
                              name: 'taggable_activity_icon',
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: [
                                    {
                                      kind: 'Literal',
                                      name: 'height',
                                      value: 16,
                                    },
                                    i,
                                    {
                                      kind: 'Literal',
                                      name: 'width',
                                      value: 16,
                                    },
                                  ],
                                  concreteType: 'Image',
                                  kind: 'LinkedField',
                                  name: 'image',
                                  plural: !1,
                                  selections: f,
                                  storageKey: null,
                                },
                                h,
                              ],
                              storageKey: null,
                            },
                            h,
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: 'inline_activities(first:1)',
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: 'WithTagsConnection',
                      kind: 'LinkedField',
                      name: 'with_tags',
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'count',
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: 'LinkedField',
                      name: 'explicit_place',
                      plural: !1,
                      selections: [
                        d,
                        {
                          alias: null,
                          args: null,
                          kind: 'ScalarField',
                          name: 'entity_id',
                          storageKey: null,
                        },
                        {
                          kind: 'InlineFragment',
                          selections: [h],
                          type: 'Node',
                          abstractKey: '__isNode',
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  type: 'Story',
                  abstractKey: null,
                },
                h,
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: b('StoriesCreateSATPPreviewQuery_facebookRelayOperation'),
          metadata: {},
          name: 'StoriesCreateSATPPreviewQuery',
          operationKind: 'query',
          text: null,
        },
      };
    })();
    e.exports = a;
  },
  null,
);
