__d(
  'LSThreadCapabilityBitOffset.bs',
  ['bs_caml_int64'],
  function (a, b, c, d, e, f) {
    'use strict';
    a = b('bs_caml_int64').zero;
    c = b('bs_caml_int64').one;
    d = [0, 2];
    e = [0, 3];
    b = [0, 4];
    var g = [0, 5],
      h = [0, 6],
      i = [0, 7],
      j = [0, 8],
      k = [0, 9],
      l = [0, 10],
      m = [0, 12],
      n = [0, 13],
      o = [0, 14],
      p = [0, 15],
      q = [0, 16],
      r = [0, 17],
      s = [0, 18],
      t = [0, 19],
      u = [0, 20],
      v = [0, 21],
      w = [0, 22],
      x = [0, 23],
      y = [0, 24],
      z = [0, 25],
      A = [0, 26],
      B = [0, 27],
      C = [0, 28],
      D = [0, 29],
      E = [0, 30],
      F = [0, 31],
      G = [0, 32],
      H = [0, 33],
      I = [0, 34],
      J = [0, 35],
      K = [0, 36],
      L = [0, 37],
      M = [0, 38],
      N = [0, 39],
      O = [0, 40],
      P = [0, 41],
      Q = [0, 42],
      R = [0, 43],
      S = [0, 44],
      T = [0, 45],
      U = [0, 46],
      V = [0, 47],
      W = [0, 48],
      X = [0, 49],
      Y = [0, 50],
      Z = [0, 51],
      $ = [0, 52],
      aa = [0, 53],
      ba = [0, 54],
      ca = [0, 55],
      da = [0, 56],
      ea = [0, 57],
      fa = [0, 58],
      ga = [0, 59],
      ha = [0, 60],
      ia = [0, 61],
      ja = [0, 62],
      ka = [0, 63],
      la = [0, 64],
      ma = [0, 65],
      na = [0, 66],
      oa = [0, 67],
      pa = [0, 68],
      qa = [0, 69],
      ra = [0, 70],
      sa = [0, 71],
      ta = [0, 72],
      ua = [0, 73],
      va = [0, 74],
      wa = [0, 75],
      xa = [0, 76],
      ya = [0, 77],
      za = [0, 78],
      Aa = [0, 79],
      Ba = [0, 80],
      Ca = [0, 81],
      Da = [0, 82],
      Ea = [0, 83],
      Fa = [0, 84],
      Ga = [0, 85],
      Ha = [0, 86],
      Ia = [0, 87],
      Ja = [0, 88],
      Ka = [0, 89],
      La = [0, 90],
      Ma = [0, 91],
      Na = [0, 92],
      Oa = [0, 93],
      Pa = [0, 94],
      Qa = [0, 95],
      Ra = [0, 96],
      Sa = [0, 97],
      Ta = [0, 98],
      Ua = [0, 99],
      Va = [0, 100],
      Wa = [0, 101],
      Xa = [0, 102],
      Ya = [0, 103],
      Za = [0, 104],
      $a = [0, 105],
      ab = [0, 106],
      bb = [0, 107],
      cb = [0, 108],
      db = [0, 109],
      eb = [0, 110],
      fb = [0, 111],
      gb = [0, 112],
      hb = [0, 113],
      ib = [0, 114],
      jb = [0, 115],
      kb = [0, 116],
      lb = [0, 118],
      mb = [0, 119],
      nb = [0, 120],
      ob = [0, 121],
      pb = [0, 122],
      qb = [0, 123],
      rb = [0, 124],
      sb = [0, 125],
      tb = [0, 126],
      ub = [0, 128],
      vb = [0, 129],
      wb = [0, 131],
      xb = [0, 132],
      yb = [0, 133],
      zb = [0, 134],
      Ab = [0, 135],
      Bb = [0, 136],
      Cb = [0, 138],
      Db = [0, 139],
      Eb = [0, 140],
      Fb = [0, 141],
      Gb = [0, 142],
      Hb = [0, 143],
      Ib = [0, 144],
      Jb = [0, 145],
      Kb = [0, 146],
      Lb = [0, 147],
      Mb = [0, 148],
      Nb = [0, 149],
      Ob = [0, 150];
    f.payment = a;
    f.camera = c;
    f.mediaPicker = d;
    f.sticker = e;
    f.gif = b;
    f.goToSecretConversation = g;
    f.colorCustomization = h;
    f.emojiCustomization = i;
    f.threadDetailsProfileButton = j;
    f.nicknames = k;
    f.block = l;
    f.calibra = m;
    f.messengerKidsManageKidAccount = n;
    f.audioClips = o;
    f.sharedMedia = p;
    f.blockGroupMember = q;
    f.feedbackAndReport = r;
    f.reactions = s;
    f.muteThread = t;
    f.seenHeads = u;
    f.messageRequestComposerBanner = v;
    f.inThreadProfileButton = w;
    f.threadDetails = x;
    f.rtcVideoCall = y;
    f.rtcVoiceCall = z;
    f.memberList = A;
    f.addMember = B;
    f.leaveThread = C;
    f.blockedUserInterstitial = D;
    f.optimisticThreadFeedbackAndReport = E;
    f.locationSharing = F;
    f.ignoreMessages = G;
    f.focusMode = H;
    f.searchInConversation = I;
    f.createGroup = J;
    f.pollCreation = K;
    f.displayActorTypeInThreadViewHeader = L;
    f.disappearingMode = M;
    f.forceOnePhaseSend = N;
    f.splitMultiSendPhoto = O;
    f.threadDetailsIgProfileButton = P;
    f.messageReply = Q;
    f.mentions = R;
    f.gamesBotThread = S;
    f.disableLinks = T;
    f.blurMedia = U;
    f.disableContextBanner = V;
    f.topLevelSelfRemediation = W;
    f.disableUserControl = X;
    f.threadDetailsShowUserName = Y;
    f.disableMessageBubbleSwipe = Z;
    f.ignoredThread = $;
    f.pageBan = aa;
    f.customThreadNotificationSounds = ba;
    f.roomCreation = ca;
    f.filePicker = da;
    f.joinRoom = ea;
    f.selfieSticker = fa;
    f.powerUp = ga;
    f.threadNameCustomization = ha;
    f.threadPhotoCustomization = ia;
    f.structuredInput = ja;
    f.suppressNullstateHeader = ka;
    f.archiveThread = la;
    f.unarchiveThread = ma;
    f.memberRequest = na;
    f.businessInboxBan = oa;
    f.ctmAdThreadWithAdWarning = pa;
    f.businessInboxSavedReplies = qa;
    f.gardenThreadSettings = ra;
    f.marketplaceSavedReplies = sa;
    f.carrierMessagingAddMember = ta;
    f.phoneCall = ua;
    f.threadDetailsDeleteThread = va;
    f.ephemeralMessageTimer = wa;
    f.messageExpiration = xa;
    f.messageSoundSettings = ya;
    f.ringtoneSoundSettings = za;
    f.hideFromActiveNow = Aa;
    f.magicWords = Ba;
    f.threadDescriptionCustomization = Ca;
    f.businessInboxCatalog = Da;
    f.adminRecallMessage = Ea;
    f.shareContact = Fa;
    f.restrictContact = Ga;
    f.soundBite = Ha;
    f.mostLikelyToPollCreation = Ia;
    f.reportChatToAdmin = Ja;
    f.canMarkReadOrUnread = Ka;
    f.businessTools = La;
    f.removeMember = Ma;
    f.groupGoToSecretConversation = Na;
    f.reportMessageToAdmin = Oa;
    f.manageMember = Pa;
    f.sharedLinks = Qa;
    f.sharedContent = Ra;
    f.addXacUsers = Sa;
    f.businessOrderManagement = Ta;
    f.rtcMarketplaceComposerBanner = Ua;
    f.isSellerRtcEligible = Va;
    f.isBuyerRtcEligible = Wa;
    f.messageLocalDelete = Xa;
    f.messageForward = Ya;
    f.isNfbEligible = Za;
    f.messageRequestGroupInvite = $a;
    f.pinnedMessagesV2 = ab;
    f.businessAppointmentBooking = bb;
    f.threadDetailsShowChatInviteLink = cb;
    f.hotlikeSticker = db;
    f.isLearningSpaceChat = eb;
    f.audioCaptions = fb;
    f.commandSilent = gb;
    f.marketplaceThreadCommerceProfileButton = hb;
    f.ephemeralMedia = ib;
    f.commandEveryone = jb;
    f.commandGif = kb;
    f.cameraBackup = lb;
    f.blockMarketplaceUser = mb;
    f.communityMessagingChannelInvite = nb;
    f.commandTextReplacement = ob;
    f.messageUnsend = pb;
    f.immersiveModesSpaces = qb;
    f.communityMessagingLinkSharingV2 = rb;
    f.communityMessagingAudioRooms = sb;
    f.bumpMessageAction = tb;
    f.cutoverBlockComposer = ub;
    f.favoriteThread = vb;
    f.bumpThread = wb;
    f.isBusinessAppointmentThreadIntentEnabled = xb;
    f.communityMessagingIcebreakers = yb;
    f.communityMessagingChannelEmojiCustomization = zb;
    f.communityMessagingChannelDescriptionCustomization = Ab;
    f.isMessengerChatEntityThread = Bb;
    f.reshareHub = Cb;
    f.reactionsV2 = Db;
    f.seenCountsV2 = Eb;
    f.isLargeThread = Fb;
    f.communityMessagingThreadLevelActivitySettings = Gb;
    f.publicChatBanUser = Hb;
    f.contentExplorer = Ib;
    f.proMode = Jb;
    f.customerAppointmentRequest = Kb;
    f.isMessengerGuideChatEntityThread = Lb;
    f.communityMessagingThreadLeaveUpsell = Mb;
    f.generatedStickers = Nb;
    f.communityMessagingContentImprovements = Ob;
  },
  null,
);
