__d(
  'CometBadge.react',
  [
    'CometVisualCompletionAttributes',
    'getCometBadgeColorStyle',
    'react',
    'stylex',
    'testID',
  ],
  function (a, b, c, d, e, f, g) {
    'use strict';
    var h = d('react'),
      i = {
        isNoneProfileBadge: { marginEnd: 'x1emribx', $$css: !0 },
        normalBorderRadius: {
          borderTopStartRadius: 'x14yjl9h',
          borderTopEndRadius: 'xudhj91',
          borderBottomEndRadius: 'x18nykt9',
          borderBottomStartRadius: 'xww2gxu',
          $$css: !0,
        },
        root: { display: 'x3nfvp2', $$css: !0 },
      },
      j = {
        dark: {
          borderTopColor: 'x1o7swki',
          borderEndColor: 'xp7cj6j',
          borderBottomColor: 'x1bkzgmd',
          borderStartColor: 'xl02xpf',
          $$css: !0,
        },
        none: {
          borderTopWidth: 'x972fbf',
          borderEndWidth: 'xcfux6l',
          borderBottomWidth: 'x1qhh985',
          borderStartWidth: 'xm0m39n',
          $$css: !0,
        },
        white: {
          borderTopColor: 'x6zyg47',
          borderEndColor: 'x1xm1mqw',
          borderBottomColor: 'xpn8fn3',
          borderStartColor: 'xtct9fg',
          $$css: !0,
        },
      },
      k = {
        6: {
          borderTopStartRadius: 'x1npaq5j',
          borderTopEndRadius: 'x1c83p5e',
          borderBottomEndRadius: 'x1enjb0b',
          borderBottomStartRadius: 'x199158v',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'x5see2y',
          borderEndWidth: 'x8ebbdf',
          borderBottomWidth: 'x1pzews7',
          borderStartWidth: 'x1r61nuk',
          height: 'xols6we',
          width: 'x1v4s8kt',
          $$css: !0,
        },
        7: {
          borderTopStartRadius: 'x1inr27j',
          borderTopEndRadius: 'x1vcqv9c',
          borderBottomEndRadius: 'xfrm7hi',
          borderBottomStartRadius: 'xpbad92',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'x1hagigm',
          width: 'xci0xqf',
          $$css: !0,
        },
        8: {
          borderTopStartRadius: 'x1lcm9me',
          borderTopEndRadius: 'x1yr5g0i',
          borderBottomEndRadius: 'xrt01vj',
          borderBottomStartRadius: 'x10y3i5r',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'xdk7pt',
          width: 'x1xc55vz',
          $$css: !0,
        },
        9: {
          borderTopStartRadius: 'x1kkc7ea',
          borderTopEndRadius: 'x1yhqcir',
          borderBottomEndRadius: 'x1hedi0j',
          borderBottomStartRadius: 'xzmsszl',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'xegnrdp',
          width: 'x1wc42o8',
          $$css: !0,
        },
        10: {
          borderTopStartRadius: 'x8u2fvd',
          borderTopEndRadius: 'x1ht7hnu',
          borderBottomEndRadius: 'x1quq95r',
          borderBottomStartRadius: 'x5yzy4c',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'x170jfvy',
          width: 'x1fsd2vl',
          $$css: !0,
        },
        12: {
          borderTopStartRadius: 'xhk9q7s',
          borderTopEndRadius: 'x1otrzb0',
          borderBottomEndRadius: 'x1i1ezom',
          borderBottomStartRadius: 'x1o6z2jb',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'x1kpxq89',
          width: 'xsmyaan',
          $$css: !0,
        },
        14: {
          borderTopStartRadius: 'x1rcc7c0',
          borderTopEndRadius: 'xbtbmw4',
          borderBottomEndRadius: 'x1lie4ck',
          borderBottomStartRadius: 'x16hxpj1',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'x1v9usgg',
          width: 'x6jxa94',
          $$css: !0,
        },
        15: {
          borderTopStartRadius: 'xu7oe1h',
          borderTopEndRadius: 'x18k2onv',
          borderBottomEndRadius: 'xlkxm3f',
          borderBottomStartRadius: 'x1ehahlu',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'xx3o462',
          width: 'x1a00udw',
          $$css: !0,
        },
        18: {
          borderTopStartRadius: 'x12myldv',
          borderTopEndRadius: 'x1udsgas',
          borderBottomEndRadius: 'xrc8dwe',
          borderBottomStartRadius: 'xxxhv2y',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'xamhcws',
          borderEndWidth: 'xol2nv',
          borderBottomWidth: 'xlxy82',
          borderStartWidth: 'x19p7ews',
          height: 'xmix8c7',
          width: 'x1xp8n7a',
          $$css: !0,
        },
        20: {
          borderTopStartRadius: 'x1a2cdl4',
          borderTopEndRadius: 'xnhgr82',
          borderBottomEndRadius: 'x1qt0ttw',
          borderBottomStartRadius: 'xgk8upj',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'x1gp4ovq',
          borderEndWidth: 'xdio9jc',
          borderBottomWidth: 'x1h2mt7u',
          borderStartWidth: 'x7g060r',
          height: 'x1qx5ct2',
          width: 'xw4jnvo',
          $$css: !0,
        },
        22: {
          borderTopStartRadius: 'x13zp6kq',
          borderTopEndRadius: 'x1mcfq15',
          borderBottomEndRadius: 'xrosliz',
          borderBottomStartRadius: 'x1wb7cse',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'x1gp4ovq',
          borderEndWidth: 'xdio9jc',
          borderBottomWidth: 'x1h2mt7u',
          borderStartWidth: 'x7g060r',
          height: 'x17rw0jw',
          width: 'x17z2i9w',
          $$css: !0,
        },
        24: {
          borderTopStartRadius: 'xyi19xy',
          borderTopEndRadius: 'x1ccrb07',
          borderBottomEndRadius: 'xtf3nb5',
          borderBottomStartRadius: 'x1pc53ja',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'x1gp4ovq',
          borderEndWidth: 'xdio9jc',
          borderBottomWidth: 'x1h2mt7u',
          borderStartWidth: 'x7g060r',
          height: 'xxk0z11',
          width: 'xvy4d1p',
          $$css: !0,
        },
        32: {
          borderTopStartRadius: 'xfh8nwu',
          borderTopEndRadius: 'xoqspk4',
          borderBottomEndRadius: 'x12v9rci',
          borderBottomStartRadius: 'x138vmkv',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'x1gp4ovq',
          borderEndWidth: 'xdio9jc',
          borderBottomWidth: 'x1h2mt7u',
          borderStartWidth: 'x7g060r',
          height: 'x10w6t97',
          width: 'x1td3qas',
          $$css: !0,
        },
        41: {
          borderTopStartRadius: 'xt49o24',
          borderTopEndRadius: 'x1rtouj8',
          borderBottomEndRadius: 'x12fpfo8',
          borderBottomStartRadius: 'x136sihb',
          borderTopStyle: 'x13fuv20',
          borderEndStyle: 'xu3j5b3',
          borderBottomStyle: 'x1q0q8m5',
          borderStartStyle: 'x26u7qi',
          borderTopWidth: 'x1gp4ovq',
          borderEndWidth: 'xdio9jc',
          borderBottomWidth: 'x1h2mt7u',
          borderStartWidth: 'x7g060r',
          height: 'x1njhlm6',
          width: 'x1r9kitl',
          $$css: !0,
        },
      },
      l = {
        6: { marginStart: 'x1w4ip6v', width: 'x1wc42o8', $$css: !0 },
        7: { marginStart: 'x1b2warb', width: 'xaw7vzs', $$css: !0 },
        8: { marginStart: 'xsgj6o6', width: 'xsmyaan', $$css: !0 },
        9: { marginStart: 'x1hvlnb8', width: 'x197psvt', $$css: !0 },
        10: { marginStart: 'x8j4wrb', width: 'x1a00udw', $$css: !0 },
        12: { marginStart: 'x1mnrxsn', width: 'x1xp8n7a', $$css: !0 },
        14: { marginStart: 'xnfveip', width: 'x1kl0l3y', $$css: !0 },
        15: { marginStart: 'xpw6ms', width: 'xpcibvc', $$css: !0 },
        18: { marginStart: 'x1cxxrxm', width: 'xo7uitg', $$css: !0 },
        20: { marginStart: 'x17adc0v', width: 'x1849jeq', $$css: !0 },
        22: { marginStart: 'x1hy63sm', width: 'x1npj6m0', $$css: !0 },
        24: { marginStart: 'x16n37ib', width: 'x14qfxbe', $$css: !0 },
        32: { marginStart: 'x1d52u69', width: 'x1useyqa', $$css: !0 },
        41: { marginStart: 'x1v860g0', width: 'x1yaf2ey', $$css: !0 },
      },
      m = {
        6: { marginStart: 'x1mnrxsn', width: 'xsmyaan', $$css: !0 },
        7: { marginStart: 'xnfveip', width: 'x6jxa94', $$css: !0 },
        8: { marginStart: 'x1i64zmx', width: 'x1kky2od', $$css: !0 },
        9: { marginStart: 'x1cxxrxm', width: 'x1xp8n7a', $$css: !0 },
        10: { marginStart: 'x17adc0v', width: 'xw4jnvo', $$css: !0 },
        12: { marginStart: 'x16n37ib', width: 'xvy4d1p', $$css: !0 },
        14: { marginStart: 'xwycmqc', width: 'xgd8bvy', $$css: !0 },
        15: { marginStart: 'x13ibhcj', width: 'x1849jeq', $$css: !0 },
        18: { marginStart: 'x1sliqq', width: 'x14qfxbe', $$css: !0 },
        20: { marginStart: 'xmn8rco', width: 'x100vrsf', $$css: !0 },
        22: { marginStart: 'x1tv9t25', width: 'x187nhsf', $$css: !0 },
        24: { marginStart: 'xmupa6y', width: 'x1useyqa', $$css: !0 },
        32: { marginStart: 'x8vdgqj', width: 'x1fu8urw', $$css: !0 },
        41: { marginStart: 'x2vb376', width: 'x1pigqs1', $$css: !0 },
      };
    function a(a) {
      var b = a.border;
      b = b === void 0 ? 'none' : b;
      var d = a.children,
        e = a.color;
      e = e === void 0 ? 'blue' : e;
      var f = a.isProfileBadge;
      f = f === void 0 ? !1 : f;
      var g = a.label,
        n = a.role,
        o = a.size;
      o = o === void 0 ? 8 : o;
      var p = a.testid,
        q = a.wide;
      q = q === void 0 ? 'normal' : q;
      return h.jsx(
        'span',
        babelHelpers['extends'](
          {
            'aria-label': g,
            className: c('stylex')(
              i.root,
              !f && i.isNoneProfileBadge,
              (g = a.colorOverride) != null
                ? g
                : c('getCometBadgeColorStyle')(e),
              k[o],
              j[b],
              q === 'wide' && l[o],
              q === 'extraWide' && m[o],
              q === 'normal' && i.normalBorderRadius,
            ),
          },
          c('testID')(p),
          c('CometVisualCompletionAttributes').IGNORE,
          { role: n, children: d },
        ),
      );
    }
    a.displayName = a.name + ' [from ' + f.id + ']';
    g['default'] = a;
  },
  98,
);
