__d(
  'LSCommunityCapabilityBitOffset.bs',
  ['bs_caml_int64'],
  function (a, b, c, d, e, f) {
    'use strict';
    a = b('bs_caml_int64').zero;
    c = b('bs_caml_int64').one;
    d = [0, 2];
    e = [0, 3];
    b = [0, 4];
    var g = [0, 5],
      h = [0, 6],
      i = [0, 7],
      j = [0, 8],
      k = [0, 9],
      l = [0, 10],
      m = [0, 11],
      n = [0, 12],
      o = [0, 13],
      p = [0, 14],
      q = [0, 15],
      r = [0, 16],
      s = [0, 17],
      t = [0, 18],
      u = [0, 19],
      v = [0, 20],
      w = [0, 21],
      x = [0, 22],
      y = [0, 23],
      z = [0, 24],
      A = [0, 25],
      B = [0, 26],
      C = [0, 27],
      D = [0, 28],
      E = [0, 29],
      F = [0, 30],
      G = [0, 31],
      H = [0, 32],
      I = [0, 33],
      J = [0, 34],
      K = [0, 35],
      L = [0, 36],
      M = [0, 37],
      N = [0, 38],
      O = [0, 39],
      P = [0, 40],
      Q = [0, 41],
      R = [0, 43],
      S = [0, 44],
      T = [0, 45],
      U = [0, 46],
      V = [0, 47],
      W = [0, 48],
      X = [0, 49],
      Y = [0, 50],
      Z = [0, 51],
      $ = [0, 52],
      aa = [0, 53],
      ba = [0, 54],
      ca = [0, 55],
      da = [0, 56],
      ea = [0, 57],
      fa = [0, 58],
      ga = [0, 59],
      ha = [0, 60],
      ia = [0, 61],
      ja = [0, 62],
      ka = [0, 63],
      la = [0, 64],
      ma = [0, 65],
      na = [0, 66],
      oa = [0, 67],
      pa = [0, 68],
      qa = [0, 69];
    f.createChannel = a;
    f.manageMember = c;
    f.adminModeration = d;
    f.fbGroupIcon = e;
    f.membersList = b;
    f.audioRoomCreation = g;
    f.blockFromCommunity = h;
    f.removeFromCommunity = i;
    f.muteMember = j;
    f.adminActions = k;
    f.channelOrganization = l;
    f.blockOneToOne = m;
    f.moderatorActions = n;
    f.viewCommunityInviteLink = o;
    f.chatImageCustomization = p;
    f.reactiveModerationInBlue = q;
    f.templateBasedChannelCreation = r;
    f.postThreadCreationActions = s;
    f.showInviteAfterCreation = t;
    f.admodBadgingInBlue = u;
    f.audioChannelCreation = v;
    f.viewCommunityChannelsInviteLinks = w;
    f.deleteChannel = x;
    f.canCreateInviteOnlyChats = y;
    f.canCreateBroadcastChats = z;
    f.audioChannelNullstate = A;
    f.canSeeAudioChannelsInList = B;
    f.inviteToCommunity = C;
    f.editCommunity = D;
    f.showSkipDialogWhenSkippingInInviteAfterCreation = E;
    f.isTopPostsEnabled = F;
    f.memberToMemberDirectInvite = G;
    f.createChatSuggestion = H;
    f.canCreateEventChatsWithDeeplinking = I;
    f.isIcebreakersEnabled = J;
    f.canViewEntityMenu = K;
    f.shouldShowNavMenuBadge = L;
    f.canEditNickname = M;
    f.createChannelAsMember = N;
    f.communityHasImplicitJoinChannel = O;
    f.shouldRemoveOptionalFieldsInManualChatCreation = P;
    f.showAdminAutocreateChatInterstitial = Q;
    f.canDeleteCommunity = R;
    f.admodNewBadgeOnCommunity = S;
    f.directInviteNonMemberCommunityLevel = T;
    f.hasMoreThanOneAdmin = U;
    f.hasMoreThanOneMember = V;
    f.canUpdateMemberRequestsApprovalSetting = W;
    f.canViewMemberRequests = X;
    f.canViewBlockedFromCommunityMemberList = Y;
    f.isCommunityBotsEnabled = Z;
    f.canCreateEventsInThread = $;
    f.communityCanSeeImprovedSettings = aa;
    f.canCreateAudioChannelEvent = ba;
    f.canViewAudioChannelEvent = ca;
    f.isHighlightsEnabled = da;
    f.directInviteNonMemberChatLevel = ea;
    f.isBadgesEnabled = fa;
    f.memberNewBadgeOnCommunity = ga;
    f.canEditContextualProfile = ha;
    f.isChatTemplateSheetEnabled = ia;
    f.canManageCommunityBots = ja;
    f.threadFullMitigations = ka;
    f.isMultiSelectChatTemplateEnabled = la;
    f.canCreateAudioChannelForCmChat = ma;
    f.canViewMemberSuggestionChannelListCta = na;
    f.hasDynamicGroupImageAdminInterstitial = oa;
    f.showOneClickChatCreation = pa;
    f.showOneClickChatCreationAfterAdminInterstitial = qa;
  },
  null,
);
