__d(
  'relay-runtime/util/RelayFeatureFlags',
  [],
  function (a, b, c, d, e, f) {
    'use strict';
    a = {
      ENABLE_CLIENT_EDGES: !1,
      ENABLE_VARIABLE_CONNECTION_KEY: !1,
      ENABLE_PARTIAL_RENDERING_DEFAULT: !0,
      ENABLE_REACT_FLIGHT_COMPONENT_FIELD: !1,
      ENABLE_RELAY_RESOLVERS: !1,
      ENABLE_GETFRAGMENTIDENTIFIER_OPTIMIZATION: !1,
      ENABLE_FRIENDLY_QUERY_NAME_GQL_URL: !1,
      ENABLE_LOAD_QUERY_REQUEST_DEDUPING: !0,
      ENABLE_DO_NOT_WRAP_LIVE_QUERY: !1,
      ENABLE_NOTIFY_SUBSCRIPTION: !1,
      BATCH_ASYNC_MODULE_UPDATES_FN: null,
      ENABLE_CONTAINERS_SUBSCRIBE_ON_COMMIT: !1,
      MAX_DATA_ID_LENGTH: null,
      STRING_INTERN_LEVEL: 0,
      USE_REACT_CACHE: !1,
      USE_REACT_CACHE_LEGACY_TIMEOUTS: !0,
      ENABLE_QUERY_RENDERER_SET_STATE_PREVENTION: !1,
    };
    e.exports = a;
  },
  null,
);
